default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: doorkeeper_development

test:
  <<: *default
  database: doorkeeper_test

production:
  <<: *default
  database: doorkeeper_production
  name: doorkeeper
  password: <%= ENV['DOORKEEPER_DATABASE_PASSWORD'] %>
